name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Copy site to output directory
        run: |
          rm -rf output || true
          mkdir output
          # copy site files to output, exclude git and workflow files
          rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' ./ output/

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
