name: Deploy to GitHub Pages (push to gh-pages)

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare site directory
        run: |
          rm -rf build || true
          mkdir -p build
          # copy site files to build, exclude git and workflow files
          rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' ./ build/

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
